name: Jendela10

on:
  workflow_dispatch:

jobs:
  build:
    name: Built Connection
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest https://raw.githubusercontent.com/dprised/jendela/main/dload.bat -OutFile dload.bat
          cmd /c dload.bat

      - name: Log In To AnyDesk
        run: cmd /c sload.bat

      - name: Time Counter
        run: Start-Sleep -Seconds 21300
